# New Brunswick
nb <- list(
    name = "nb",
    code = "13",
    
    reader = function(path) {
        readxl::read_xlsx(path) %>%
            set_names(str_to_lower(names(.))) %>% # set names to lowercase
            mutate_if(is.POSIXct, as_date) %>% # readxl uses POSIXct objects for dates so we convert to Date objects to match metabase
            mutate_if(is.character, str_to_lower) # make all character cols lower case
    },  
    
    mapper = function(cases_df){
        cases_df %>% 
            rename(ptcaseid = `p/tcase_id`,
                   reporteddate = reported_date,
                   testingreason = reason_for_testing,
                   testingreasonspec = if_other_testing_specify_reason,
                   classification = case_classification,
                   residencecountry = `if_non-canadian_ resident_which_country`,
                   detectedatentry = detected_at_point_of_entry,
                   dateofentry = if_yes_date_of_entry, 
                   poinofentrylocation = if_yes_location_of_entry,
                   age = age_years, #also age_months but all na, if used would need logic
                   indigenous = does_case_identify_as_aboriginal,
                   indigenousgroup = if_yes_indicate_which_group,
                   reserve = does_case_reside_on_first_nations_reseve_most_of_the_time,
                   occupation = case_occupation,
                   occupationspec = other_specify,
                   onsetdate = `section 2.symptoms_onset_date`,
                   hosp = hospitalization,
                   hospstartdate = if_hospitalized_admission_date,
                   #discharged	
                   hospenddate = discharge_date,
                   icustartdate = if_admitted_to_icu_admission_date,
                   #discharged_icu	
                   icuenddate = discharge_date_from_icu,
                   isolation = isolation_negative_pressure,
                   isolationstartdate = start_date_of_isolation,
                   isolationenddate = end_date_of_isolation,
                   mechanicalvent = mechanical_ventilation,
                   ventstartdate = start_date_of_mechanical_ventilation,
                   ventenddate = end_date_of_mechanical_ventilation,
                   #end_of_ventilation
                   disposition = `current disposition`,
                   #final_disposition	if_other_disposition_specify	
                   recoverydate = final_disposition_date, #check
                   deathresp = if_deceased_death_attributed_to_respiratory_illness,
                   deathcause = cause_of_death,
                   deathdate = date_of_death,
                   closecontactcase = `prior_to_sx_was_case_in_close_contact_with_confirmed/probable`,
                   closecontactcaseidspt = if_yes_specify_case_id,
                   closecontactcasedatefirst = date_of_first_contact,
                   closecontactcasedate = date_of_last_contact,
                   closecontactcasesetting = if_yes_specify_contact_setting,
                   closecontactcasesettingspec = `if_other setting_specify`,
                   closecontactother = `prior_sx_case_closecontact_person_fever/cough_affect_area`,
                   closecontactotherdate = if_yes_date_of_last_contact,
                   closecontactothersetting = if_yes_specify_contact_setting_2,
                   closecontactothersettingspec = `if_other setting_specify_2`,
                   closecontactotherloc = exposure_occurred_in_canada,
                   closecontactotherlocspec = if_no_specify,
                   animalcontact = `prior_sx_case_contact_liveanimal/animalproducts_affect_area`,
                   animalcontactspec = if_yes_specify_animal_or_animal_product,
                   animalcontactsetting = if_yes_where,
                   animalcontactsettingcity = specify_city,
                   healthfacilityexposure = prior_to_sx_did_case_visit_healthcare_facility,
                   numberofcontacts = number_of_close_contacts_identified,
                   symcough = cough, 
                   symfever = fever,
                   symchills = `feverish_chills_(temperatire_not_taken)`,
                   symsorethroat = sore_throat,
                   symrunnynose = runny_nose,
                   symshortnessofbreath = shortness_of_breath_difficulty_breathing,
                   symnausea = nausea_vomiting,
                   symheadache = headache,
                   symweakness = general_weakness,
                   sympain = `pain_(nuscular_chest_abdominal_joint_etc)`,
                   symirritability = irritability_confusion,
                   symdiarrhea = diarrhea,
                   symother = other_symptoms,
                   symotherspec = `other_specify symptoms`,
                   rfcardiacdisease = cardiac_disease,
                   rfneurodisorder = chronic_neurological_neuromuscular_disorder,
                   rfdiabetes = diabetes,
                   rfimmunodef = immunodeficiency_disease_condition,
                   rfliverdisease = liver_disease,
                   rfmalignancy = malignancy,
                   rfpostpartum = post_partum,
                   rfpregnancy = pregnancy,
                   rfpregtrimester = if_yes_trimester,
                   rfrenaldisease = renal_disease,
                   rfother = `other_conditions_risk factors`,
                   dxlungausc = abnormal_lung_auscultation,
                   dxmentalstatus = altered_mental_status,
                   dxpneumonia = clinical_radiological_evidence_of_pneumonia,
                   dxcoma = coma,
                   dxconjunctinjection = conjuctival_injection,
                   dxards =  `diagnosed_with_ards`,
                   dxdyspnea =  `o2_saturation_<95%`,
                   dxencephalitis = encephalitis,
                   dxhypotension = hypotension,
                   dxpharyngeal = pharyngeal_exudate,
                   dxrenalfailure = renal_failure,
                   dxseizure = seizure,
                   dxsepsis = sepsis,
                   dxtachypnea = tachypnea,
                   dxother = other_diagnoses,
                   dxotherspec = `if_other _diagnoses_specify`,
                   travelfromcountry1 = if_travelled_location_of_origin_1,
                   traveltocountry1 = if_travelled_location_of_destination_1,
                   travelstartdate1 = if_travelled_start_date_1,
                   travelenddate1 = if_travelled_end_date_1,
                   travelhotel1 = if_travelled_specify_hotel_residence_1,
                   travelflight1 = if_travelled_specify_flight_details_1,
                   travelfromcountry2 = if_travelled_location_of_origin_2,
                   traveltocountry2 = if_travelled_location_of_destination_2,
                   travelstartdate2 = if_travelled_start_date_2,
                   travelenddate2 = if_travelled_end_date_2,
                   travelhotel2 = if_travelled_specify_hotel_residence_2,
                   travelflight2 = if_travelled_specify_flight_details_2,
                   travelfromcountry3 = if_travelled_location_of_origin_3,
                   traveltocountry3 = if_travelled_location_of_destination_3,
                   travelstartdate3 = if_travelled_start_date_3,
                   travelenddate3 = if_travelled_end_date_3,
                   travelhotel3 = if_travelled_specify_hotel_residence_3,
                   travelflight3 = if_travelled_specify_flight_details_3,
                   travelfromcountry4 = if_travelled_location_of_origin_4,
                   traveltocountry4 = if_travelled_location_of_destination_4,
                   travelstartdate4 = if_travelled_start_date_4,
                   travelenddate4 = if_travelled_end_date_4,
                   travelhotel4 = if_travelled_specify_hotel_residence_4,
                   travelflight4 = if_travelled_specify_flight_details_4,
                   labid1 = lab_id_specimen1,
                   labspecimentype1 = `type/source_specimen1`,
                   labspecimencollectiondate1 = collection_date_specimen1,
                   labtestmethod1 = test_method_specimen1,
                   labtestresult1 = test_result_specimen1,
                   labtestresultdate1 = test_date_speciment1,
                   labid2 = lab_id_specimen2,
                   labspecimencollectiondate2 = collection_date_specimen2,
                   labspecimentype2 = `type/source_specimen2`,
                   labtestmethod2 = test_method_specimen2,
                   labtestresult2 = test_result_specimen2,
                   labtestresultdate2 = test_date_speciment2,
                   labid3 = lab_id_specimen3,
                   labspecimencollectiondate3 = collection_date_specimen3,
                   labspecimentype3 = `type/source_specimen3`,
                   labtestmethod3 = test_method_specimen3,
                   labtestresult3 = test_result_specimen3,
                   labtestresultdate3 = test_date_speciment3,
                   labid4 = lab_id_specimen4,
                   labspecimencollectiondate4 = collection_date_specimen4,
                   labspecimentype4 = `type/source_specimen4`,
                   labtestmethod4 = test_method_specimen4,
                   labtestresult4 = test_result_specimen4,
                   labtestresultdate4 = test_date_speciment4,
                   labid5 = lab_id_specimen5,
                   labspecimencollectiondate5 = collection_date_specimen5,
                   labspecimentype5 = `type/source_specimen5`,
                   labtestmethod5 = test_method_specimen5,
                   labtestresult5 = test_result_specimen5,
                   labtestresultdate5 = test_date_speciment5,
                   nmlconfirmation = nml_confirmatory_test,
                   nmlconfirmationdate = date_nml_confirmation,
                   travel_domestic = prior_to_onset_did_case_travel_outside_of_nb_inside_canada

            ) %>% 
            mutate(pt = "nb") %>% 
            mutate(ageunit = "years") %>%
            rename(travel1 = matches("traveltocountry")) %>% 
            rename(travel2 = matches("travelfromcountry")) %>% 
            mutate(across(matches("travel[0-9]{2}"), list(international_loc = parse_location, domestic_loc = parse_province))) %>% 
            mutate(fsa = "not collected") %>% 
            mutate(racespec = "not collected") %>% 
            mutate(indigenousidentityspec = "not collected") %>% 
            mutate(deathcause = "not collected") %>% 
            mutate(closecontactother = "not collected") %>% 
            mutate(closecontactotherspec = "not collected")
    }
)
